config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"

  # Defines a route for the path "/about"
  # get "/route", to: "controller#action" as:HelperName

  get('/welcome', { to: 'welcome#index', as: 'welcome' })
  get('/goodbye', { to: 'welcome#goodbye', as: 'goodbye' })
  # get('/goodbye', { to: 'welcome#goodbye', as: :tata })
  get('/form_example', { to: 'welcome#form_example', as: 'form_example' })
  # get('/example/:id') # /example/1

  # Routes for questions
#  get "/questions/new", to: "questions#new", as: :new_question
#  post "/questions" => "questions#create", as: :questions
#  get "/questions/:id" => "questions#show", as: :question
#  get "/questions" => "questions#index"
#  get "/questions/:id/edit" => "questions#edit", as: :edit_question
#  patch "/questions/:id" => "questions#update", as: :update_question
#  delete "/questions/:id" => "questions#destroy", as: :delete_question

resources :questions do
  resources :answers, only: [:create, :destroy]
end

resource :sessions

resources :users, only: [:new, :create]

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord

    #  a Question has many answers
    # when a Question object is deleted, all of its associated Answer objects should also be deleted
    has_many :answers, dependent: :destroy

    validates :title, presence: true, uniqueness: {message: "needs to be unique!"}
    validates :body, length: {minimum: 5, maximum: 100} 

    # custom validation
    validate :no_monkey
    validate :no_title_in_body

    belongs_to :user, optional: true

    # life cycle events
    before_save {
        # before saving it to db capitalize the title
        self.title = title.capitalize
    }

    before_validation(:set_default_view_count)

    # Scope: Scopes are class methods for Model
    # scope(:name_of_method, ->{lambda})
    scope(:recent_ten, ->{ order("created_at desc").limit(10) })
    # The above is equivalent to:
    # def self.recent_ten
    #     order("created_at desc").limit(10)
    # end

    def self.search(keyword)
        where('title ILIKE ? or body ILIKE ?', "%"+keyword+"%", "%"+keyword+"%")
    end

    private
    # custom validation method
    def no_monkey
        if body && body.downcase.include?("monkey")
            self.errors.add(:body, "must not contain monkey")
        end
    end

    def no_title_in_body
        if body&.downcase.include?(title.downcase)
            self.errors.add(:body, "must not include title of question")
        end
    end

    def set_default_view_count
        self.view_count ||=0
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :questions
    has_many :answers

    def full_name
        "#{first_name} #{last_name}"
    end

    validates :email, presence: true
    validates :first_name, presence: true
    validates :last_name, presence: true


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
        before_action :authenticate_user!, except: [:index, :show]

    def create
        question_id = params[:question_id]
        @question = Question.find(question_id)
        answer_params = params.require(:answer).permit(:body)
        @answer = Answer.new answer_params
        @answer.question = @question
        @answer.user = current_user

        if @answer.save
            redirect_to question_path(@question)
        else
            render 'questions/show'
        end
    end

    def destroy
        question_id = params[:question_id]
        @question = Question.find(question_id)
        @answer = Answer.find(params[:id])
        @answer.destroy
        redirect_to question_path(@question)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!
        redirect_to new_sessions_path unless user_signed_in?
    end

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
    helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def new
        @question = Question.new
    end

    def create
        quesiton_params = params.require(:question).permit(:title, :body)
        @question = Question.new quesiton_params
        @question.user = current_user

        if @question.save
            redirect_to question_path(@question)
        else 
            render :new
        end
    end

    def show
        @question = Question.find(params[:id])
        @answer = Answer.new
    end

    def index
        @questions = Question.order(created_at: :desc)
    end

    def edit
        @question = Question.find(params[:id])
    end

    def update
        @question = Question.find(params[:id])
        question_params = params.require(:question).permit(:title, :body)

        if @question.update(question_params)
            redirect_to question_path(@question)
        else
            render :edit
        end
    end

    def destroy
        @question = Question.find(params[:id])
        @question.destroy
        redirect_to questions_path
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id # Log in the user
      redirect_to root_path, notice: "Logged in!"
    else
      flash[:alert] = "Wrong credentials"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil # Log out the user
    redirect_to sessions_new_path, notice: "Logged out!"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged In!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    # inside the controller, we can define actions
    def index
       
    end

    def goodbye
    end

    def form_example
    end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeAnswers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Awesome Answers", welcome_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

     <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", welcome_path, class:"nav-link" %>
      </li>
            <li class="nav-item active">
        <%= link_to "Questions", questions_path, class:"nav-link" %>
      </li>
  <% if user_signed_in? %>
    Hello <%= current_user.full_name %> 
    <%= link_to "Logout", sessions_destroy_path, method: :delete, class:"nav-link" %>
  <% else %>
    <%= link_to "Login", sessions_new_path, class: "nav-link" %> 
    <%= link_to "Sign Up", users_new_path, class: "nav-link" %> 
  <% end %>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h2>Edit Question</h2>
<% if @question.errors.any? %>
    <ul>
        <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_for @question do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<h2>All Questions</h2>

<%= button_to "New Question", new_question_path, :method => :get %>
<% @questions.each do |question| %>
    <div>
    <h3><%= link_to(question.title, question_path(question)) %></h3>
    <p>
    <%= truncate(question.body, length: 100) %>
    </p>
    </div>
<% end %>

app/views/questions/new.html.erb
<h2>Ask a Question</h2>
<% if @question.errors.any? %>
  <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @question, data: { turbo: false } do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class:"form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class:"form-control" %>
    </div>

    <%= f.submit, class: "btn btn-outline-primary" %>
<% end %>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>
<h3><%= @question.body %></h3>
  <% if @question.user %>
  <small>Asked by <%= @question.user.full_name %> </small>
  <% end %>
<p><%= @question.created_at %></p>

<%= button_to "Edit", edit_question_path(@question), :method => :get %>
<%= button_to "Delete", @question, method: :delete %>

<% @question.answers.each do |answer| %>
  <div>
  <%= answer.body %> 
  <% if answer.user %>
  <small> Answered by <%= answer.user.full_name %> </small>
  <% end %>
  <small> Answered <%= time_ago_in_words(answer.created_at) %> ago </small>
  <%= button_to "Delete", [@question, answer], method: :delete %>
  </div>
  <hr>
<% end %>

<%= form_for [@question, @answer], data: { turbo: false } do |f| %>
    <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>

    <%= f.submit %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user, data: { turbo: false } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <%= f.submit :Submit, class: 'btn btn-primary'%>
<% end %>

app/views/welcome/form_example.html.erb
<h1>Form Example</h1>

<%= form_with do |form| %>
    form contents here
    <br />
    <%= form.label :name, "Name:" %>
    <%= form.text_field :name %>
    <%= form.label :email, "Email:" %>
    <%= form.text_field :email %>
    <%= form.submit "Submit" %>
<% end %>

app/views/welcome/goodbye.html.erb
<h1>Goodbye!</h1>

app/views/welcome/index.html.erb
<h1>Welcome To The Awesome Answers!!</h1>